version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: track_user
      POSTGRES_PASSWORD: track_pass
      POSTGRES_DB: trackworkout
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: .
    restart: always
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://track_user:track_pass@db:5432/trackworkout
    depends_on:
      - db

volumes:
  db_data:
